"""Add performance indexes

Revision ID: 4e1f1ca4145d
Revises: e0758d195f9b
Create Date: 2026-07-25 13:19:34.090649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1f1ca4145d'
down_revision: Union[str, Sequence[str], None] = 'e0758d195f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_procurement_requests_created_at'), 'procurement_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_procurement_requests_status'), 'procurement_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procurement_requests_status'), table_name='procurement_requests')
    op.drop_index(op.f('ix_procurement_requests_created_at'), table_name='procurement_requests')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    # ### end Alembic commands ###
