"""Add procurement_request_vendors table

Revision ID: 8e3c0b29bb3a
Revises: beffb1a4ed07
Create Date: 2026-07-24 18:46:49.991734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3c0b29bb3a'
down_revision: Union[str, Sequence[str], None] = 'beffb1a4ed07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_request_vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('procurement_request_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['procurement_request_id'], ['procurement_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_request_vendors_procurement_request_id'), 'procurement_request_vendors', ['procurement_request_id'], unique=False)
    op.create_index(op.f('ix_procurement_request_vendors_vendor_id'), 'procurement_request_vendors', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procurement_request_vendors_vendor_id'), table_name='procurement_request_vendors')
    op.drop_index(op.f('ix_procurement_request_vendors_procurement_request_id'), table_name='procurement_request_vendors')
    op.drop_table('procurement_request_vendors')
    # ### end Alembic commands ###
