"""Add Call models

Revision ID: beffb1a4ed07
Revises: f9e66ebbf188
Create Date: 2026-07-24 03:31:52.792072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beffb1a4ed07'
down_revision: Union[str, Sequence[str], None] = 'f9e66ebbf188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('agent_task_id', sa.UUID(), nullable=True),
    sa.Column('call_provider', sa.String(), nullable=True),
    sa.Column('external_call_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_task_id'], ['agent_tasks.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_agent_task_id'), 'calls', ['agent_task_id'], unique=False)
    op.create_index(op.f('ix_calls_external_call_id'), 'calls', ['external_call_id'], unique=False)
    op.create_index(op.f('ix_calls_organization_id'), 'calls', ['organization_id'], unique=False)
    op.create_index(op.f('ix_calls_vendor_id'), 'calls', ['vendor_id'], unique=False)
    op.create_table('call_transcripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_table('vendor_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('procurement_request_id', sa.UUID(), nullable=True),
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('delivery_time', sa.String(), nullable=True),
    sa.Column('warranty', sa.String(), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['procurement_request_id'], ['procurement_requests.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_offers_organization_id'), 'vendor_offers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_vendor_offers_procurement_request_id'), 'vendor_offers', ['procurement_request_id'], unique=False)
    op.create_index(op.f('ix_vendor_offers_vendor_id'), 'vendor_offers', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_offers_vendor_id'), table_name='vendor_offers')
    op.drop_index(op.f('ix_vendor_offers_procurement_request_id'), table_name='vendor_offers')
    op.drop_index(op.f('ix_vendor_offers_organization_id'), table_name='vendor_offers')
    op.drop_table('vendor_offers')
    op.drop_table('call_transcripts')
    op.drop_index(op.f('ix_calls_vendor_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_organization_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_external_call_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_agent_task_id'), table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
